name: Deploy
on:
  push:
    tags: ['v*']

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/jdks
            ~/.gradle/native
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew -Dorg.gradle.parallel=true publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --stacktrace
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Get tag name
        id: get_tag
        shell: bash
        run: |
          tag_name="$(echo $GITHUB_REF | cut -d / -f 3)"
          echo ::set-output name=tag::$tag_name
      - name: Generate release changelog
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true
          stripGeneratorNotice: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: 'Release ${{ steps.get_tag.outputs.tag }}'
          body: ${{ steps.generate-release-changelog.outputs.changelog }}
          prerelease: false
          draft: false
          files: |
            hypo-asm/build/libs/*.jar
            hypo-asm/hypo-asm-hydrate/build/libs/*.jar
            hypo-core/build/libs/*.jar
            hypo-hydrate/build/libs/*.jar
            hypo-mappings/build/libs/*.jar
            hypo-model/build/libs/*.jar
